version: "3.8"
services:
  api:
    build: ./api #to the path where DockerFile is located
    container_name: api_c
    ports:
      - "5000:4000"
    volumes:
      - ./api:/app
      - ./app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - "4000:3000"
    volumes:
      - ./myblog:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
